name: social

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: docker build -f ./social_media_vite_app/Dockerfile -t ghcr.io/${{ github.repository_owner }}/social:latest ./social_media_vite_app

      - name: Push Image
        run: docker push ghcr.io/${{ github.repository_owner }}/social:latest